adding CI, CD, config mgmt. testing content
cdfoundation/best-practices-site pull request #4
Opened 2022-03-11 21:17 UTC by tequilarista

2022-03-11 21:31 UTC, tdcox commented
@tequilarista Should this chapter https://deploy-preview-4--preview-site-cdf-bp.netlify.app/learn/cd/ be entitled ‘Continuous Deployment’?

2022-03-11 21:41 UTC, tdcox commented
Some of the links are broken at the top of the page in the ‘integration’ and ‘testing’ chapters.

I think we need to expand on testing in a subsequent iteration but other than that it looks good for a first pass.

We will come back and look at layout and styling as a whole, later.

2022-03-13 23:15 UTC, tequilarista commented
> 

Ah, good catch.  Continuous Delivery is more common, but deployments (if I recall this particular conversation correctly), was felt to be more precise/accurate.

Let me take another stab at that...

2022-03-14 01:07 UTC, tdcox commented
Yeah, I think from our glossary that we agreed that Continuous Delivery was the preferred term for the overarching methodology and Continuous Deployment refers to the step of releasing each build.

2022-04-05 18:35 UTC, justinabrahms requested changes
I think a lot of your "why" sections are actually "what is the historical context that lead to this being generally accepted as a good idea". This is super useful!  It's different than "Why should I care about continuous integration?", which is what the title says (to me) that it will be about.

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/cd/_index.md
> +## Approval and Approval Gates {#heading-approval}
This seems to be talking about human approvals. I often think of "quality gates" as things which increase our feeling of safety of a deploy as it passes through, like a filter. Should be file a ticket to add something like that to this section?

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/ci/_index.md
> +- Examples of verifications:
```suggestion
Examples of verifications:
```

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/ci/_index.md
> +Minimizing broken builds due to incompatible coding changes is the purpose of the continuous integration process. Many of us can remember the days when project teams would have a ‘sync-up’ process wh
```suggestion
Minimizing broken builds due to incompatible coding changes is the purpose of the continuous integration process. Historically, project teams would have a ‘sync-up’ process which generally meant check-in all of your coding updates and hope that the build runs successfully. An unsung hero called the Build Manager created the build script which would include merging and pulling all of the coding updates based on ‘tags’ and then get the build to run. 
```

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/ci/_index.md
> +The process of triggering the ‘build’ is sometimes referred to as the continuous build step of the CI process. This step is executed by calling a static build script created and maintained by the bui
the 'build manager' thing mentioned here makes it sound like it's still a human as before.

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/ci/_index.md
> +Compile by Branch - for every build, a branch is referenced. The branch name is passed to the build step to determine what to pull for the compile/link.
I'm not sure if it's just me, but "compile/link" doesn't fit many languages I work with (js, python). I wonder if that might be offputting to folks somehow?

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/ci/_index.md
> +### Know your Merging Strategy
only having a single subheading, it might just be worth omitting the previous paragraph and this heading, and pulling the content below up?

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/ci/_index.md
> +1. A build should create not only the binaries, but also the application package named based on a version numbering schema that relates back to the versioning Tag. (MSI, zip, rpm, or container image)
```suggestion
1. A build should create not only the binaries, but also the application package named based on a version schema that relates back to the versioning Tag. (MSI, zip, rpm, or container image)
```

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/ci/_index.md
> +2. A full Bill of Material report should be required at minimum for all production releases. BOM reports are often undervalued, but they are key to debugging issues if needed. A BOM report should sho
```suggestion
2. A full Bill of Material report should be required at minimum for all production releases. BOM reports are key to debugging issues if needed. A BOM report should show:
```

I think saying they're undervalued reduces the value of this statement. Just tell folks this is what we do, and I think it has more oomph.

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/config/_index.md
> +# Best Practices {#heding-bp}
```suggestion
# Best Practices {#heading-bp}
```

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/config/_index.md
> +Included in your software build process or container image build is the need for defining transitive dependencies. This step is needed to identify vulnerabilities, licenses usage and policy conforman
```suggestion
Included in your software build process or container image build is the need for defining transitive dependencies. This step is needed to identify vulnerabilities, licenses usage and policy conformance in open source libraries on which your software depends.  
```

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/config/_index.md
> +Understanding the impact a single source code change has on the consuming applications is critical in understanding the risk level of an update. In a cloud native environment the impact of a microser
```suggestion
Understanding the impact a single source code change has on the consuming applications is critical in understanding the risk level of an update. In a cloud native environment, the impact of a microservice update is only exposed at run-time. The ability to view the impact or blast radius prior to a release will minimize the runtime incidents in both a monolithic or microservice architecture. In addition, when changing the infrastructure, a clear understanding of the potential risk of an update is needed. 
```

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/config/_index.md
> +Variables relate to how the binaries, containers and runtime environments are configured. Whether you are running in a traditional server based environment or cloud native environment, environment va
Isn't this just config?

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/config/_index.md
> +
```suggestion
```

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/config/_index.md
> +While not apparent, there are particular configuration requirements for a Service Oriented Architecture (SOA) that can significantly simplify the change management process. Minimizing the sprawl of s
spell out DDD the first time?

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/testing/_index.md
> +Description/Scope
stray heading or something?

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/testing/_index.md
> +Allow testers to work alongside developers throughout the software development and delivery process. Note that "tester" is a role, not necessarily a full-time job. Perform manual test activities such
In a world where every commit goes through automated build/test and on to production.. how does a tester work w/ them "throughout" the process? Seems like it would necessarily be afterwards, unless we're suggesting manual testing be a blocker for PR merge?

2022-04-05 18:35 UTC, justinabrahms commented on content/en/learn/testing/_index.md
> +size of the staging cluster, sometimes it’s a single machine used as a cluster
I think you want bullets here.

2022-04-18 16:21 UTC, tdcox commented
@tequilarista The subchapter on 'Continuous Deployment' is still incorrectly showing entitled as 'Continuous Delivery' in the preview.

2022-04-26 08:36 UTC, tdcox commented
Bulk content now LGTM. Merging so that we can start to accept other contributions.

We can iterate on the detail as part of the subsequent review process, as discussed.

2022-04-26 08:36 UTC, merged